-- AlterTable
ALTER TABLE `Job` MODIFY `status` ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'WAITING_FOR_PICKUP', 'WAITING_FOR_PAYMENT', 'CANCELLED', 'WONT_DO', 'WAITING') NOT NULL DEFAULT 'NOT_STARTED';

-- AlterTable
ALTER TABLE `JobItem` MODIFY `status` ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'WAITING_FOR_PICKUP', 'WAITING_FOR_PAYMENT', 'CANCELLED', 'WONT_DO', 'WAITING') NOT NULL DEFAULT 'NOT_STARTED';
