-- AlterTable
ALTER TABLE `logs` MODIFY `type` ENUM('USER_LOGIN', 'USER_CREATED', 'SHOP_CREATED', 'USER_CONNECTED_TO_SHOP', 'USER_DISCONNECTED_FROM_SHOP', 'USER_SHOP_ROLE_CHANGED', 'USER_PROMOTED_TO_ADMIN', 'USER_DEMOTED_FROM_ADMIN', 'USER_SUSPENSION_APPLIED', 'USER_SUSPENSION_REMOVED', 'USER_SUSPENSION_CHANGED') NOT NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `suspended` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `suspensionReason` VARCHAR(191) NULL;
