-- AlterTable
ALTER TABLE `logs` ADD COLUMN `billingGroupId` VARCHAR(191) NULL,
    ADD COLUMN `billingGroupProjectFileId` VARCHAR(191) NULL,
    ADD COLUMN `billingGroupProjectId` VARCHAR(191) NULL,
    ADD COLUMN `userBillingGroupId` VARCHAR(191) NULL,
    MODIFY `type` ENUM('USER_LOGIN', 'USER_CREATED', 'SHOP_CREATED', 'USER_CONNECTED_TO_SHOP', 'USER_DISCONNECTED_FROM_SHOP', 'USER_SHOP_ROLE_CHANGED', 'USER_PROMOTED_TO_ADMIN', 'USER_DEMOTED_FROM_ADMIN', 'USER_SUSPENSION_APPLIED', 'USER_SUSPENSION_REMOVED', 'USER_SUSPENSION_CHANGED', 'JOB_CREATED', 'JOB_MODIFIED', 'JOB_DELETED', 'JOB_STATUS_CHANGED', 'JOB_ITEM_CREATED', 'JOB_ITEM_DELETED', 'JOB_ITEM_MODIFIED', 'JOB_ITEM_STATUS_CHANGED', 'JOB_FINALIZED', 'JOB_INVOICE_GENERATED', 'RESOURCE_CREATED', 'RESOURCE_MODIFIED', 'RESOURCE_DELETED', 'RESOURCE_IMAGE_CREATED', 'RESOURCE_IMAGE_MODIFIED', 'RESOURCE_IMAGE_DELETED', 'RESOURCE_TYPE_CREATED', 'RESOURCE_TYPE_MODIFIED', 'RESOURCE_TYPE_DELETED', 'MATERIAL_CREATED', 'MATERIAL_MODIFIED', 'MATERIAL_DELETED', 'MATERIAL_MSDS_UPLOADED', 'MATERIAL_TDS_UPLOADED', 'MATERIAL_IMAGE_CREATED', 'MATERIAL_IMAGE_MODIFIED', 'MATERIAL_IMAGE_DELETED', 'COMMENT_CREATED', 'LEDGER_ITEM_CREATED', 'LEDGER_ITEM_CREATED_MANUALLY', 'BILLING_GROUP_CREATED', 'BILLING_GROUP_MODIFIED', 'BILLING_GROUP_DELETED', 'USER_ADDED_TO_BILLING_GROUP', 'USER_REMOVED_FROM_BILLING_GROUP', 'USER_BILLING_GROUP_ROLE_CHANGED', 'BILLING_GROUP_PROJECT_CREATED', 'BILLING_GROUP_PROJECT_MODIFIED', 'BILLING_GROUP_PROJECT_DELETED', 'BILLING_GROUP_PROJECT_FILE_UPLOADED') NOT NULL;

-- CreateTable
CREATE TABLE `BillingGroup` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` MEDIUMTEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `shopId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `UserBillingGroup` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `billingGroupId` VARCHAR(191) NOT NULL,
    `role` ENUM('ADMIN', 'MEMBER') NOT NULL DEFAULT 'MEMBER',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BillingGroupProject` (
    `id` VARCHAR(191) NOT NULL,
    `billingGroupId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BillingGroupProjectFile` (
    `id` VARCHAR(191) NOT NULL,
    `fileKey` VARCHAR(191) NOT NULL,
    `fileUrl` VARCHAR(191) NOT NULL,
    `fileName` VARCHAR(191) NOT NULL,
    `fileType` VARCHAR(191) NOT NULL,
    `BillingGroupProjectId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_billingGroupId_fkey` FOREIGN KEY (`billingGroupId`) REFERENCES `BillingGroup`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_userBillingGroupId_fkey` FOREIGN KEY (`userBillingGroupId`) REFERENCES `UserBillingGroup`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_billingGroupProjectId_fkey` FOREIGN KEY (`billingGroupProjectId`) REFERENCES `BillingGroupProject`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_billingGroupProjectFileId_fkey` FOREIGN KEY (`billingGroupProjectFileId`) REFERENCES `BillingGroupProjectFile`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BillingGroup` ADD CONSTRAINT `BillingGroup_shopId_fkey` FOREIGN KEY (`shopId`) REFERENCES `Shop`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `UserBillingGroup` ADD CONSTRAINT `UserBillingGroup_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `UserBillingGroup` ADD CONSTRAINT `UserBillingGroup_billingGroupId_fkey` FOREIGN KEY (`billingGroupId`) REFERENCES `BillingGroup`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BillingGroupProject` ADD CONSTRAINT `BillingGroupProject_billingGroupId_fkey` FOREIGN KEY (`billingGroupId`) REFERENCES `BillingGroup`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BillingGroupProjectFile` ADD CONSTRAINT `BillingGroupProjectFile_BillingGroupProjectId_fkey` FOREIGN KEY (`BillingGroupProjectId`) REFERENCES `BillingGroupProject`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
