name = "stl-renderer"
main = "stl-renderer.js"
compatibility_date = "2024-11-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
RENDER_TOKEN = "COREDESK_RENDER_TOKEN"   # must match server env

[browser]
binding = "BROWSER"

[observability]
[observability.logs]
enabled = false
invocation_logs = true