-- AlterTable
ALTER TABLE `logs` ADD COLUMN `commentId` VARCHAR(191) NULL,
    MODIFY `type` ENUM('USER_LOGIN', 'USER_CREATED', 'SHOP_CREATED', 'USER_CONNECTED_TO_SHOP', 'USER_DISCONNECTED_FROM_SHOP', 'USER_SHOP_ROLE_CHANGED', 'USER_PROMOTED_TO_ADMIN', 'USER_DEMOTED_FROM_ADMIN', 'USER_SUSPENSION_APPLIED', 'USER_SUSPENSION_REMOVED', 'USER_SUSPENSION_CHANGED', 'JOB_CREATED', 'JOB_MODIFIED', 'JOB_DELETED', 'JOB_STATUS_CHANGED', 'JOB_ITEM_CREATED', 'JOB_ITEM_DELETED', 'JOB_ITEM_MODIFIED', 'JOB_ITEM_STATUS_CHANGED', 'RESOURCE_CREATED', 'RESOURCE_MODIFIED', 'RESOURCE_DELETED', 'RESOURCE_IMAGE_CREATED', 'RESOURCE_IMAGE_MODIFIED', 'RESOURCE_IMAGE_DELETED', 'RESOURCE_TYPE_CREATED', 'RESOURCE_TYPE_MODIFIED', 'RESOURCE_TYPE_DELETED', 'MATERIAL_CREATED', 'MATERIAL_MODIFIED', 'MATERIAL_DELETED', 'MATERIAL_MSDS_UPLOADED', 'MATERIAL_TDS_UPLOADED', 'MATERIAL_IMAGE_CREATED', 'MATERIAL_IMAGE_MODIFIED', 'MATERIAL_IMAGE_DELETED', 'COMMENT_CREATED') NOT NULL;

-- CreateTable
CREATE TABLE `JobComment` (
    `id` VARCHAR(191) NOT NULL,
    `message` MEDIUMTEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_commentId_fkey` FOREIGN KEY (`commentId`) REFERENCES `JobComment`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `JobComment` ADD CONSTRAINT `JobComment_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `Job`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `JobComment` ADD CONSTRAINT `JobComment_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
