-- AlterTable
ALTER TABLE `logs` ADD COLUMN `printer3dMaterialId` VARCHAR(191) NULL,
    ADD COLUMN `printer3dTypeId` VARCHAR(191) NULL,
    MODIFY `type` ENUM('USER_LOGIN', 'USER_CREATED', 'SHOP_CREATED', 'USER_CONNECTED_TO_SHOP', 'USER_DISCONNECTED_FROM_SHOP', 'USER_SHOP_ROLE_CHANGED', 'USER_PROMOTED_TO_ADMIN', 'USER_DEMOTED_FROM_ADMIN', 'USER_SUSPENSION_APPLIED', 'USER_SUSPENSION_REMOVED', 'USER_SUSPENSION_CHANGED', 'JOB_CREATED', 'JOB_MODIFIED', 'JOB_DELETED', 'JOB_STATUS_CHANGED', 'JOB_ITEM_CREATED', 'JOB_ITEM_DELETED', 'JOB_ITEM_MODIFIED', 'JOB_ITEM_STATUS_CHANGED', 'RESOURCE_CREATED', 'RESOURCE_MODIFIED', 'RESOURCE_DELETED', 'RESOURCE_IMAGE_CREATED', 'RESOURCE_IMAGE_MODIFIED', 'RESOURCE_IMAGE_DELETED', 'PRINTER_3D_TYPE_CREATED', 'PRINTER_3D_TYPE_MODIFIED', 'PRINTER_3D_TYPE_DELETED', 'PRINTER_3D_MATERIAL_CREATED', 'PRINTER_3D_MATERIAL_MODIFIED', 'PRINTER_3D_MATERIAL_DELETED') NOT NULL;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_printer3dTypeId_fkey` FOREIGN KEY (`printer3dTypeId`) REFERENCES `Printer3dType`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `logs` ADD CONSTRAINT `logs_printer3dMaterialId_fkey` FOREIGN KEY (`printer3dMaterialId`) REFERENCES `Printer3dMaterial`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
