-- AlterTable
ALTER TABLE `UserShop` ADD COLUMN `accountTitle` VARCHAR(191) NULL,
    ADD COLUMN `accountType` ENUM('CUSTOMER', 'OPERATOR', 'ADMIN', 'INSTRUCTOR') NOT NULL DEFAULT 'CUSTOMER';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `admin` BOOLEAN NOT NULL DEFAULT false;
