name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Install Dependencies
        working-directory: ./api
        run: yarn install

      - name: Run Integration Tests
        working-directory: ./api
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/sluop-test
          JWT_SECRET: TEST_JWT_SECRET
          BASE_URL: "http://localhost:5173"
        run: yarn test
